eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#      instance:
#        hostname: clientName
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Clq010101
    url: jdbc:mysql://47.105.152.65:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  port: 9091